version: '3'
services:
  mongodb:
    image: mongo
    container_name: db
    restart: unless-stopped
    ports:
      - "27016:27017"
    volumes:
      - ./db:/data/db
    networks:
      - db-network
  
  backend:
    container_name: backend
    env_file:
      .env
    build: 
      context: ./backend
      dockerfile: Dockerfile
      args:
        - DATABASE=${DATABASE}
        - PORT=${PORT}
        - SECRET=${SECRET}
        - TOKEN_DURATION=${TOKEN_DURATION}
        - GITHUB_SECRET=${GITHUB_SECRET}
        - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
        - GITHUB_CALLBACK_URL=${GITHUB_CALLBACK_URL}
    ports:
      - "3000:3000"
    # volumes:
    #   - ./backend:/usr/src/app
    networks:
      - db-network
    links:
      - mongodb

volumes:
  db:

networks:
  db-network:
    driver: bridge
