version: '3'
services:
  mongodb:
    image: mongo
    restart: unless-stopped
    ports:
      - "27016:27017"
    volumes:
      - ./db:/data/db
    networks:
      - db-network

  # mongo-seed:
  #   build: ./mongo-seed
  #   links:
  #     - mongodb
  #   depends_on:
  #     - mongodb

  backend:
    env_file:
      .env
    build: 
      context: ./backend
      dockerfile: Dockerfile
      args:
        - DATABASE=${DATABASE}
        - PORT=${PORT}
        - SECRET=${SECRET}
        - TOKEN_DURATION=${TOKEN_DURATION}
        - GITHUB_SECRET=${GITHUB_SECRET}
        - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
        - GITHUB_CALLBACK_URL=${GITHUB_CALLBACK_URL}
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    networks:
      - db-network
    links:
      - mongodb

volumes:
  db:

networks:
  db-network:
    driver: bridge
